name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
repository: https://github.com/flutter/plugins/tree/main/packages/video_player/video_player
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.4.5

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: video_player_android
      ios:
        default_package: video_player_avfoundation
      web:
        default_package: video_player_web

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  video_player_android:
    git:
      url: https://github.com/gismart/flutter-plugins.git
      path: packages/video_player/video_player_android
      ref: video_player-gismart
  video_player_avfoundation:
    git:
      url: https://github.com/gismart/flutter-plugins.git
      path: packages/video_player/video_player_avfoundation
      ref: video_player-gismart
  video_player_platform_interface:
    git:
      url: https://github.com/gismart/flutter-plugins.git
      path: packages/video_player/video_player_platform_interface
      ref: video_player-gismart
  video_player_web:
    git:
      url: https://github.com/gismart/flutter-plugins.git
      path: packages/video_player/video_player_web
      ref: video_player-gismart

dev_dependencies:
  flutter_test:
    sdk: flutter
